// Shader that shows how environmental reflections works

// Contrary to the specular reflection that are only generated by the mian light source, ambient reflections are generated by each light
// ray hitting a surface, including bouncing from all angles.

// Of course this means that calculating those type of reflections in real-time use a lot of GPU power. To avoid that we can use a cubemap texture
// to apply pre-calculated reflections. Inside Unity we can use a reflection probe to generate this reflection cubemap.

Shader "LearnShader/Lighting/Environmental Reflection"
{
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
        
        // Keyword enum to choose between a reflection from cubemap or skybox
        [KeywordEnum(Cubemap, Skybox)] _ReflectionSource ("Reflection source", float) = 1
        
        // Ambient Reflections properties
        [Header(Cubemap parameters)]
        _ReflectionTex ("Reflection Texture", Cube) = "white" {}
        _ReflectionInt ("Reflection Intensity", Range(0,1)) = 1
        _ReflectionMet ("Reflection Metallic", Range(0,1)) = 0
        [IntRange]_ReflectionLod ("Reflection Level of detail", Range(1,9)) = 1
        _ReflectionExp ("Reflection Exposure", Range(1,3)) = 0
    }
    SubShader
    {
        Tags {
            "RenderType"="Opaque"
            "LightMode"="ForwardBase" // Since reflection is lighting pass we need to configure the render path
        }
        LOD 100

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_fog
            
            #pragma shader_feature _REFLECTIONSOURCE_CUBEMAP _REFLECTIONSOURCE_SKYBOX

            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
                float3 normal : NORMAL; // Get normal
            };

            struct v2f
            {
                float2 uv : TEXCOORD0;
                UNITY_FOG_COORDS(1)
                float4 vertex : SV_POSITION;
                float3 normal_world : TEXCOORD1; // Pass normal to frag() in worldSpace
                float3 vertex_world : TEXCOORD2; // vertex position in world space to calculate view direction
            };

            sampler2D _MainTex;
            float4 _MainTex_ST;
            
            // Ambient reflection connection variables
            samplerCUBE _ReflectionTex;
            float _ReflectionInt;
            float _ReflectionMet;
            half _ReflectionLod;
            float _ReflectionExp;
            
            float3 AmbientReflection(samplerCUBE colorRefl, float reflectionInt, half reflectionLod, float3 normal, float3 viewDir, float reflectionExp)
            {
                viewDir = -viewDir; // we need to negate view dir otherwise reflections are upside down
                float3 reflection_world = reflect(viewDir, normal); // reflect(): reflect a vector using another vector as simmetry axis
                
                // sample cubemap with a specified level of details (LOD level is W component of the sample coordinates)
                float4 cubemap = texCUBElod(colorRefl, float4(reflection_world, reflectionLod));
                
                return reflectionInt * cubemap.rgb * (cubemap.a * reflectionExp);
            }

            v2f vert (appdata v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = TRANSFORM_TEX(v.uv, _MainTex);
                UNITY_TRANSFER_FOG(o,o.vertex);
                o.normal_world = UnityObjectToWorldNormal(v.normal); // convert the normal to world-space
                o.vertex_world = mul(unity_ObjectToWorld, v.vertex); // convert vertex position to world-space
                return o;
            }

            fixed4 frag (v2f i) : SV_Target
            {
                fixed4 col = tex2D(_MainTex, i.uv);

                // Ambient reflection parameters
                half3 normal = i.normal_world;
                half3 viewDir = normalize(UnityWorldSpaceViewDir(i.vertex_world)); // UnityWorldSpaceViewDir() is a UnityCG.cginc function that calculate view direction from vertex world position
                
            // Use a cubemap texture to define reflection
            #if _REFLECTIONSOURCE_CUBEMAP
                // Calculate ambient reflection
                half3 reflection = AmbientReflection(_ReflectionTex, _ReflectionInt, _ReflectionLod, normal, viewDir, _ReflectionExp);
                
                // Apply reflection to texture
                col.rgb *= reflection + _ReflectionMet;
                
            // Use UNITY_SAMPLE_TEXCUBE to define reflection
            #elif _REFLECTIONSOURCE_SKYBOX
                // Calculate reflection direction
                half3 reflect_world = reflect(-viewDir, normal); // negate view dir to prevent upside down reflections
                
                // Sample default reflection cubemap
                // -> UNITY_SAMPLE_TEXCUBE macro sample the data using the refelction coordinates
                // -> unity_SpecCube[n] contains the data of Unity default reflection probe
                half4 reflectionData = UNITY_SAMPLE_TEXCUBE(unity_SpecCube0, reflect_world);
                
                // Decode the color in HDR using DecodeHDR() (is part of UnityCG.cginc)
                half3 reflectionColor = DecodeHDR(reflectionData, unity_SpecCube0_HDR);
                
                col.rgb *= reflectionColor;
            #endif
                
                UNITY_APPLY_FOG(i.fogCoord, col);
                return col;
            }
            ENDCG
        }
    }
}
