// Shader to explore compute shader  structure

// Compute Shader

// -> A compute shader is a program that can run data algorithms directly on the graphics card. Since GPU excels at doing lots of small calculation
//    parallelly we can use compute shader to generate high quality effects or to process operations that are not necessarily graphic but require
//    calculations of millions of vertices or multiple instances of an object.

// -> A compute shader has its own graphical pipeline which is not part of a regular rendering pipeline, however since the shader is part of Direct3D/openGL
//    APIm it can link the output directly over a classic render pipeline.

// -> For example Ray-tracing and sphere tracing are both advanced techniques that rely on compute shader to process heavy operations on the GPU. Both of them
//    relies on tracing ray inside a scene to determine the object's distance to the camera position. This task is decomposed in 3 parts: ray generation (start point),
//    ray intersection (hit position on the object), shading (Illumination, shadow and surface).
// -> The integration of this type of technique requires High-end GPU and are not compatible with low-end or mobile devices.

// Structure of a compute shader

// -> The structure of a compute shader is similar to an unlit or a surface shader but it does not include the built-in variables that make programming easier.
// -> A compute shader is composed of:
//      - a "kernel" of the "CSMain" function
//      - a 2d texture for writing a reading called "Result"
//      - a number of threads used to process the texture texel ("numthread")
//      - a "CSMain" function that includes a semantic as argument and return a RGBA color saved in the Result 2D texture

// 
// Default Compute Shader code commented
//

// Kernel
// -> Pragma directive that declare a function to compile (like "#pragma vertex vert" tells vert() is the vertex shader)
// -> Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Result 2D texture
// -> this texture is used to write and read the result of the CSMain function we declared
// -> since the texture has read/write capability, it allows data to be sent from the CPU to the GPU, be processed in parallel and returned
RWTexture2D<float4> Result;
// -> If we need extra variable that only need write access we declare the variable without the RW prefix:
//      ex: Texture2d<float4> WriteVariable;

// Numthread
// -> Define the number of threads we must use to process CSMain and calculate the texels of our Result texture
// -> numthreads(X,Y,Z): To tell the number of thread we want to use we specify the number of column on X axis (X), row on Y axis (Y) and depth on the Z-axis (Z).
//      - For example numthreads(8,8,1) means we use 8 columns on X axis, 8 rows on Y axis and 1 set on Z axis
//      - To calculate the number of thread used we just multiply all the axis together (X * Y * Z = number of threads)
// -> By default, the program has a group of 64 threads (8 * 8 * 1 = 64). 
// -> Warps: to work with threads the hardware subdivide the groups into sub-blocks called Warps, the number of total group must be a multiple of the warp size:
//      - Nvidia use a multiple of the warp size (32 threads per group)
//      - ATI use a multiple of the wavefront size (64 threads per group)
//      => this is the reason unity default numthreads X and Y values are 8, it ensure compatibility with Nvidia and ATI 
[numthreads(8,8,1)]
// CSMain function
// -> Actual declaration and body of the function defined by the #pragma kernel directive
// -> This contains all the operations we want to process on the GPU
// -> The function use a semantic as argument and return its result inside the Result texture we declared early
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
