
#pragma kernel CSMain

struct Cube
{
    float3 localPosition;
    float4 color;
};

RWStructuredBuffer<Cube> cubes; // Use the structured buffer as output
float resolution;
float repetitions;
float maxZOffset;

// pseudo random function that return a number between 0 and 1
float rand(float2 co)
{
    return (frac(sin(dot(co.xy, float2(12.9898, 78.233))) * 43758.5453)) * 1;
}

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float u = id.x/resolution; // id.x remapped to [0.0,1.0]
    Cube cube = cubes[id.x];

    for (int i = 0; i < repetitions; ++i)
    {
        float zPos = rand(float2(u, cube.localPosition.z));
        zPos = -maxZOffset + zPos * (maxZOffset - -maxZOffset); // Remap random from [0,1] to [-maxZOffset, maxZOffset]
        cube.localPosition.z = zPos;
    
        float r = rand(float2(cube.color.r, cube.color.g));
        float g = rand(float2(cube.color.g, cube.color.b));
        float b = rand(float2(cube.color.b, cube.color.r));
        cube.color = float4(r, g, b, 1);
    }
    
    cubes[id.x] = cube;
}
