// Compute shader that ...

// How to use a compute shader

// -> Just like a vertex-fragment shader use shaderlab to communicate between Unity and CGPROGRAM/HLSLPROGRAM, a compute shader require to be associated with a c# script that will
//    allow to declare global variables and buffers that we will be able to connect with the CG/HLSL code.
// -> the function that is in charge of executing CSMain kernel is called "Dispatch()". It launch a certain number of thread in it XYZ dimensions.

// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "ShaderToHuman/s2h.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
 RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Result.GetDimensions(width, height);
    
    // Simple implementation of shader to human
    ContextGather ui;
    s2h_init(ui, id.xy+0.5);
    s2h_setCursor(ui, float2(width/2, height/2));
    s2h_setScale(ui, 1.0f);
    s2h_printTxt(ui, _H, _e, _l, _l, _o);
    s2h_printLF(ui);
    s2h_printTxt(ui, _W, _o, _r, _l, _d);
    s2h_printBox(ui, float4(1,0,0,0));
    
    // all texels are blue
    //Result[id.xy] = float4(0,0,1,1);
    
    // Test to change value to get scale the grid displayed
    //Result[id.xy] = float4((id.x &7)/7, (id.y &7)/7, 0,0);
    
    // Default calculation
    // -> create a graphical representation of the sierpinski triangle (https://en.wikipedia.org/wiki/Sierpi%C5%84ski_triangle)
    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0) + ui.dstColor;
}
